"""
Database and output locations for the pipeline
"""

### OUTPUT DIRs
FLAGS = os.path.join(OUTPUT, 'FLAGS')

SR = os.path.join(OUTPUT, 'SR')
LR = os.path.join(OUTPUT, 'LR')

BENCHMARKS = os.path.join(OUTPUT, 'BENCHMARKS')

REAL = os.path.join(OUTPUT, 'REAL')
SIMULATED = os.path.join(OUTPUT, 'SIMULATED')
QUAST = os.path.join(OUTPUT, 'QUAST')


# flye 
# real
HYBRACTER_OUTPUT_REAL = os.path.join(REAL, 'HYBRACTER_OUTPUT')

# simulated
HYBRACTER_OUTPUT_SIMULATED = os.path.join(SIMULATED, 'HYBRACTER_OUTPUT')

HYBRACTER_OUTPUT_TESTS = os.path.join(OUTPUT, 'HYBRACTER_TESTS')

# unicycler
# real
UNICYCLER_OUTPUT_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT')

#sim
UNICYCLER_OUTPUT_SIMULATED = os.path.join(REAL, 'UNICYCLER_OUTPUT_SIMULATED')

###########################
# QUAST
##################

# QUAST REFS

QUAST_REFS = os.path.join(QUAST, 'QUAST_REFS')

# unicycler 
# directory holds the unicycler plasmids only to not overstate unicycler's inaccuracy

UNICYCLER_PLASMIDS_ONLY = os.path.join(QUAST, 'UNICYCLER_PLASMIDS_ONLY')
# real
UNICYCLER_PLASMIDS_ONLY_1_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_REAL')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_REAL = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_REAL')

# sim
UNICYCLER_PLASMIDS_ONLY_1_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_1_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_8_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_8_THREADS_SIM')
UNICYCLER_PLASMIDS_ONLY_16_THREADS_SIM = os.path.join(UNICYCLER_PLASMIDS_ONLY, 'UNICYCLER_OUTPUT_16_THREADS_SIM')

# QUAST unicycler

QUAST_UNICYCLER_1_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')

QUAST_UNICYCLER_1_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')


# QUAST PLASSEMBLER FLYE

QUAST_PLASSEMBLER_FLYE_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_FLYE_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_FLYE_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# raven
QUAST_PLASSEMBLER_RAVEN_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_RAVEN_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_RAVEN_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')


#real
QUAST_PLASSEMBLER_FLYE_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_FLYE_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_FLYE_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# raven
QUAST_PLASSEMBLER_RAVEN_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
QUAST_PLASSEMBLER_RAVEN_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
QUAST_PLASSEMBLER_RAVEN_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')



