"""
Database and output locations for the pipeline
"""

### OUTPUT DIRs
FLAGS = os.path.join(OUTPUT, 'FLAGS')

SR = os.path.join(OUTPUT, 'SR')
LR = os.path.join(OUTPUT, 'LR')

BENCHMARKS = os.path.join(OUTPUT, 'BENCHMARKS')

REAL = os.path.join(OUTPUT, 'REAL')
SIMULATED = os.path.join(OUTPUT, 'SIMULATED')
QUAST = os.path.join(OUTPUT, 'QUAST')


# flye 
# real
HYBRACTER_LONG_OUTPUT_REAL = os.path.join(REAL, 'HYBRACTER_LONG_OUTPUT')
HYBRACTER_HYBRID_OUTPUT_REAL = os.path.join(REAL, 'HYBRACTER_HYBRID_OUTPUT')


# simulated
HYBRACTER_LONG_OUTPUT_SIMULATED = os.path.join(SIMULATED, 'HYBRACTER_LONG_OUTPUT')
HYBRACTER_HYBRID_OUTPUT_SIMULATED = os.path.join(SIMULATED, 'HYBRACTER_HYBRID_OUTPUT')


# for install
HYBRACTER_OUTPUT_TESTS = os.path.join(OUTPUT, 'HYBRACTER_TESTS')

# unicycler
# real
UNICYCLER_OUTPUT_REAL = os.path.join(REAL, 'UNICYCLER_OUTPUT')

#sim
UNICYCLER_OUTPUT_SIMULATED = os.path.join(REAL, 'UNICYCLER_OUTPUT_SIMULATED')


###########################
# QUAST
##################

# QUAST REFS

QUAST_REFS = os.path.join(QUAST, 'QUAST_REFS')

# QUAST unicycler

QUAST_UNICYCLER_1_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_REAL = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')

QUAST_UNICYCLER_1_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_1_THREADS')
QUAST_UNICYCLER_8_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_8_THREADS')
QUAST_UNICYCLER_16_THREADS_SIMULATED = os.path.join(QUAST, 'UNICYCLER_OUTPUT_16_THREADS')


# # QUAST PLASSEMBLER FLYE

# QUAST_PLASSEMBLER_FLYE_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
# QUAST_PLASSEMBLER_FLYE_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
# QUAST_PLASSEMBLER_FLYE_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# # raven
# QUAST_PLASSEMBLER_RAVEN_1_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
# QUAST_PLASSEMBLER_RAVEN_8_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
# QUAST_PLASSEMBLER_RAVEN_16_THREADS_SIMULATED = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')


# #real
# QUAST_PLASSEMBLER_FLYE_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_1_THREADS')
# QUAST_PLASSEMBLER_FLYE_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_8_THREADS')
# QUAST_PLASSEMBLER_FLYE_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_FLYE_OUTPUT_16_THREADS')

# # raven
# QUAST_PLASSEMBLER_RAVEN_1_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_1_THREADS')
# QUAST_PLASSEMBLER_RAVEN_8_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_8_THREADS')
# QUAST_PLASSEMBLER_RAVEN_16_THREADS_REAL = os.path.join(QUAST, 'PLASSEMBLER_RAVEN_OUTPUT_16_THREADS')



